name: reastaurant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  flutter_rating_bar: ^4.0.1
  google_fonts: ^8.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  workmanager: ^0.9.0+3
  rxdart: ^0.27.7
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
